package io.github.andrewwwwwwwwwwwwwww.tbextra;

/**
 * Bounding box of each backpack model, in block space, matching the geometry the client
 * draws. Generated by tools/genquads.js - do not edit by hand.
 */
public final class BackpackBounds {
    /** Corner-to-corner extent of a pack, in block units. */
    public record Bounds(float x0, float y0, float z0, float x1, float y1, float z1) {
        public float width() {
            return x1 - x0;
        }

        public float height() {
            return y1 - y0;
        }

        public float depth() {
            return z1 - z0;
        }

        /** Largest dimension, used to size packs consistently against each other. */
        public float longestEdge() {
            return Math.max(width(), Math.max(height(), depth()));
        }
    }

    private BackpackBounds() {
    }

    public static Bounds of(String backpack) {
        return switch (backpack) {
            case "firewatch" -> new Bounds(0.18171F, 0.0F, 0.29142F, 0.81829F, 0.875F, 0.70858F);
            case "trapper" -> new Bounds(-0.01143F, 0.0F, 0.28801F, 1.01143F, 0.875F, 0.71199F);
            default -> throw new IllegalArgumentException("Unknown backpack: " + backpack);
        };
    }
}
